In [87]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
#knn.kneighbors probar

In [88]:
X_iris = pd.DataFrame(iris['data'], columns=iris['feature_names'])
X_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [89]:
X_y_iris = X_iris.copy()
X_y_iris['target'] = iris['target']
X_y_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_iris, iris['target'], test_size=0.2, random_state=33)

In [91]:
pd.DataFrame(y_train).value_counts(normalize=True)

0
0    0.35
1    0.35
2    0.30
Name: proportion, dtype: float64

In [92]:
pd.DataFrame(y_test).value_counts(normalize=True)


0
2    0.466667
0    0.266667
1    0.266667
Name: proportion, dtype: float64

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X_iris, iris['target'], stratify=iris['target'], test_size=0.2, random_state=33)

In [94]:
pd.DataFrame(y_train).value_counts(normalize=True)

0
0    0.333333
1    0.333333
2    0.333333
Name: proportion, dtype: float64

In [95]:
pd.DataFrame(y_test).value_counts(normalize=True)

0
0    0.333333
1    0.333333
2    0.333333
Name: proportion, dtype: float64

In [96]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [97]:
from sklearn.metrics import accuracy_score, multilabel_confusion_matrix, classification_report, recall_score, precision_score
accuracy_score(y_train, knn.predict(X_train))

0.975

In [98]:
multilabel_confusion_matrix(y_train, knn.predict(X_train))

array([[[80,  0],
        [ 0, 40]],

       [[79,  1],
        [ 2, 38]],

       [[78,  2],
        [ 1, 39]]], dtype=int64)

In [99]:
classification_report(y_train, knn.predict(X_train), target_names=iris['target_names'], output_dict=True)

{'setosa': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 40.0},
 'versicolor': {'precision': 0.9743589743589743,
  'recall': 0.95,
  'f1-score': 0.9620253164556962,
  'support': 40.0},
 'virginica': {'precision': 0.9512195121951219,
  'recall': 0.975,
  'f1-score': 0.9629629629629629,
  'support': 40.0},
 'accuracy': 0.975,
 'macro avg': {'precision': 0.9751928288513655,
  'recall': 0.975,
  'f1-score': 0.974996093139553,
  'support': 120.0},
 'weighted avg': {'precision': 0.9751928288513655,
  'recall': 0.975,
  'f1-score': 0.9749960931395532,
  'support': 120.0}}

In [100]:
accuracy_score(y_test, knn.predict(X_test))

0.9333333333333333

In [101]:
multilabel_confusion_matrix(y_test, knn.predict(X_test))

array([[[20,  0],
        [ 0, 10]],

       [[19,  1],
        [ 1,  9]],

       [[19,  1],
        [ 1,  9]]], dtype=int64)

In [102]:
classification_report(y_test, knn.predict(X_test), target_names=iris['target_names'], output_dict=True)

{'setosa': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 10.0},
 'versicolor': {'precision': 0.9,
  'recall': 0.9,
  'f1-score': 0.9,
  'support': 10.0},
 'virginica': {'precision': 0.9,
  'recall': 0.9,
  'f1-score': 0.9,
  'support': 10.0},
 'accuracy': 0.9333333333333333,
 'macro avg': {'precision': 0.9333333333333332,
  'recall': 0.9333333333333332,
  'f1-score': 0.9333333333333332,
  'support': 30.0},
 'weighted avg': {'precision': 0.9333333333333333,
  'recall': 0.9333333333333333,
  'f1-score': 0.9333333333333333,
  'support': 30.0}}

In [103]:
X_test[:1]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                5.7               2.9                4.2               1.3

In [104]:
knn.predict(X_test[:1])

array([1])

In [105]:
y_test[:1]

array([1])

In [106]:
import numpy as np

X_train["dist_euc"] = X_iris.apply(lambda x: np.linalg.norm(x-X_test[:1]), axis=1)

In [107]:
X_train_ = X_train.copy()
X_train_['target_names'] = y_train
X_train_.sort_values("dist_euc").head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
99                5.7               2.8                4.1               1.3   
88                5.6               3.0                4.1               1.3   

    dist_euc  target_names  
95  0.141421             1  
99  0.141421             1  
88  0.173205             1

In [108]:
X_test[:1]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                5.7               2.9                4.2               1.3

In [109]:
((X_test[:1].values - X_train.sort_values("dist_euc").head(1).values[:, :-1])**2).sum()**0.5

0.14142135623730964

In [110]:
knn.kneighbors(X_test[:1], n_neighbors=3)

(array([[0.14142136, 0.14142136, 0.17320508]]),
 array([[104,  46,  97]], dtype=int64))

In [113]:
X_train.drop(columns=['dist_euc'], inplace=True, errors='ignore')
l_a = []
for n in range(1, 8):
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train, y_train)
    l_a.append(accuracy_score(y_test, knn.predict(X_test)))

In [119]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_train_std = pd.DataFrame(X_train_std, columns=iris['feature_names'])
X_train_std

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.542920         -0.124289           0.418077          0.393693
1             0.557180         -0.569505           0.757440          0.393693
2            -1.154087          0.098318          -1.278740         -1.312310
3             0.312714         -1.014720           1.040243          0.262462
4             1.168347          0.320926           1.209925          1.443541
..                 ...               ...                ...               ...
115          -0.909620          1.656572          -1.052498         -1.049848
116           0.679414         -0.569505           1.040243          1.312310
117          -1.031853         -0.124289          -1.222179         -1.312310
118          -0.909620          0.988749          -1.335300         -1.181079
119          -1.031853          1.211357          -1.335300         -1.312310

[120 rows x 4 columns]

In [120]:
l_a = []
X_test_std = std.transform(X_test)
X_test_std = pd.DataFrame(X_test_std, columns=iris['feature_names'])
for n in range(1, 8):
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train_std, y_train)
    l_a.append(accuracy_score(y_test, knn.predict(X_test_std)))

In [121]:
l_a

[0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333]

In [118]:
minmax = MinMaxScaler()
X_train_minmax = minmax.fit_transform(X_train)
X_train_minmax = pd.DataFrame(X_train_minmax, columns=iris['feature_names'])
X_train_minmax

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.305556          0.416667           0.593220          0.583333
1             0.555556          0.333333           0.694915          0.583333
2             0.166667          0.458333           0.084746          0.041667
3             0.500000          0.250000           0.779661          0.541667
4             0.694444          0.500000           0.830508          0.916667
..                 ...               ...                ...               ...
115           0.222222          0.750000           0.152542          0.125000
116           0.583333          0.333333           0.779661          0.875000
117           0.194444          0.416667           0.101695          0.041667
118           0.222222          0.625000           0.067797          0.083333
119           0.194444          0.666667           0.067797          0.041667

[120 rows x 4 columns]

In [122]:
l_a = []
X_test_minmax = minmax.transform(X_test)
X_test_minmax = pd.DataFrame(X_test_minmax, columns=iris['feature_names'])
for n in range(1, 8):
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train_minmax, y_train)
    l_a.append(accuracy_score(y_test, knn.predict(X_test_minmax)))

In [124]:
l_a

[0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333]

In [125]:
l_a = []
for n in range(1, 8):
    knn = KNeighborsClassifier(n_neighbors=n, metric='manhattan')
    knn.fit(X_train, y_train)
    l_a.append(accuracy_score(y_test, knn.predict(X_test)))

In [126]:
knn.kneighbors(X_test[:1], n_neighbors=3)

(array([[0.2, 0.2, 0.3]]), array([[104,  46,  97]], dtype=int64))

In [127]:
X_test[:1]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                5.7               2.9                4.2               1.3

In [ ]:
X_train["dist_manh"] = X_train.apply(lambda x: abs((x - X_test[:1])).sum())