## Reto 1: Hundir la Flota (Batalla Naval)
### Objetivo: Implementar una versión simplificada del juego de Batalla Naval usando Python y Numpy para manejar el tablero del juego.

- Crear un tablero 10x10 usando Numpy arrays.
- Colocar 5 barcos de diferentes tamaños en posiciones aleatorias en el tablero.
- Permitir que el jugador ingrese coordenadas para "disparar".
- Mostrar un mensaje si el jugador acierta o falla, y actualizar el tablero acorde.
- Seguir jugando hasta que todos los barcos sean hundidos.
#### Habilidades aplicadas: Uso de arrays de Numpy, generación de números aleatorios, estructuras de control en Python.

In [2]:
import numpy as np

# Creamos el tablero

tablero = np.full((10, 10), 0)

def colocacion_de_barcos(dimension_barco, tablero):
    colocacion = np.random.choice(["horizontal", "vertical"]) # Establecemos donde y como de colocara el barco

    if colocacion == "horizontal": # Dependiendo se si es horizontal o vertical modificaremos la fila o la columna, para evitar que el barco se salga de tablero
        columna = np.random.randint(10 - dimension_barco) # Esto es la forma de que el barco nunca se pase del tablero, por ejemplo, al estar en horizontal, sus elementos nunca se saldrian del tablero verticalmente, por lo que las filas no habra que modificala
        fila = np.random.randint(10) 
        lista = list(tablero[fila, columna:dimension_barco + columna] == 0) # Esta comparacion compara 1 por 1 todos los elementos y devuelve una lista de booleanos
        if False in lista: # si hay algun False en la lista significa que en al menos un punto hay un barco.
            colocacion_de_barcos(dimension_barco, tablero) 

        else: # En este caso, la fila sera de todo 0 por lo que podremos poner el barco sin ningun problema
            tablero[fila, columna:dimension_barco + columna] = dimension_barco # le damos el valor de la dimension para poder distinguir entre barcos y que todos sera de diferente tamaño
            return tablero

    elif colocacion == "vertical": # Caso en el que la colocacion sea vertical, idem pero cambiando, horizontal por verticaal y fila por columna
        fila = np.random.randint(10 - dimension_barco)
        columna = np.random.randint(10)  
        lista = list(tablero[fila:dimension_barco + fila, columna] == 0) 
        if False in lista:
            colocacion_de_barcos(dimension_barco, tablero)
                 
        else:
            tablero[fila:dimension_barco + fila, columna] = dimension_barco
            return tablero
        
def creacion_de_tablero():
    tablero = np.full((10, 10), 0)
    barcos = [2,3,4,5,7]
    for i in barcos:
        tablero = colocacion_de_barcos(i, tablero)
    return tablero

print(creacion_de_tablero())

[[0 0 0 0 0 3 0 0 0 0]
 [0 4 4 4 4 3 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 7 7 7 7 7 7 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 5 5 5 5 5 0 0 0]]
