# Ejercicio 1

<img src ='https://estaticos-cdn.prensaiberica.es/clip/23bf0054-14a8-40d0-8700-dc653638d702_16-9-discover-aspect-ratio_default_0.jpg' width=300>

Rafa, Nacho y Clara quieren comprar palmeras, donuts, hojaldres y tartas. Cada uno necesita diferentes cantidades y pueden elegir dos tiendas: *Manolo Bakes* y *Starbucks*. 

Las siguiente tablas muestran, respectivamente, la cantidad que cada uno necesita, y los precios en cada una de las tiendas

<table><thead><tr><th></th><th>Palmeras</th><th>Donuts</th><th>Hojaldres</th><th>Tartas</th></tr></thead><tbody><tr><td>Rafa</td><td>6</td><td>5</td><td>3</td><td>1</td></tr><tr><td>Nacho</td><td>3</td><td>6</td><td>2</td><td>2</td></tr><tr><td>Clara</td><td>3</td><td>4</td><td>3</td><td>1</td></tr></tbody></table>

<table><thead><tr><th></th><th>Manolo Bakes</th><th>Starbucks</th></tr></thead><tbody><tr><td>Palmera</td><td>1.50</td><td>1.00</td></tr><tr><td>Donut</td><td>2.00</td><td>2.50</td></tr><tr><td>Hojaldre</td><td>5.00</td><td>4.50</td></tr><tr><td>Tarta</td><td>16.00</td><td>17.00</td></tr></tbody></table>

Por ejemplo, si Rafa compra en *Manolo Bakes* gastaría:  

$6\cdot1.50+5\cdot2+3\cdot5+1\cdot16=50$  

y si compra en *Starbucks* gastaría:  

$6\cdot1+5\cdot2.50+3\cdot4.50+1\cdot17=49$  

**SE PIDE**: Genera la matriz que exprese la cantidad que cada persona gastaría en cada tienda, y recomienda a cada uno dónde debería hacer sus compras

In [8]:
import numpy as np

In [19]:
A = np.array([[6, 5, 3, 1],
             [3, 6, 2, 2],
             [3, 4, 3, 1]])

B = np.array ([[1.5, 1],
              [2, 2.5],
              [5, 4.5],
              [16, 17]])

R = A.dot(B)
print(R)

recom = R.argmin(axis = 1) # método para calcular min por filas en matrices. Así obtengo el índice de cada uno
print(recom)

tiendas = ["Manolo Bakes", "Starbucks"]
personas = ["Rafa", "Nacho", "Clara"]

for index, persona in enumerate(personas):
    print(persona, "debe comprar en", tiendas[recom[index]])


[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]
[1 0 0]
Rafa debe comprar en Starbucks
Nacho debe comprar en Manolo Bakes
Clara debe comprar en Manolo Bakes


In [ ]:
result = []
for el in R:
    result.append(el)
    i = 0
    j = 0
    for i,j in result:
        if result[i] > result[j+1]:
            print("Te recominedo que compres en Starbucks")
        elif result[i] < result[j+1]:
            print("Te recoiendo que compres en Manolo Bakes")
        else:
            print("Compra donde quieras, no hay diferencia")
    

# Ejercicio 2
<img src='https://i0.wp.com/contraste.info/desarrollo/wp-content/uploads/2015/04/Marsattacks_FichaCine_5566706.jpg?fit=260%2C180&ssl=1' width="300">
                                                                                                
Hemos sido invadidos por los extraterrestres. El Gobierno ha prohibido toda comunicación escrita en castellano. Para poder comunicarnos, debemos generar mensajes de hasta 9 letras, codificados conforme al siguiente diccionario:

```Python
{'A':8,
 'B':7,
 'C':5,
 'D':13,
 'E':9,
 'F':16,
 'G':18,
 'H':22,
 'I':4,
 'J':23,
 'K':11,
 'L':3,
 'M':21,
 'N':1,
 'O':6,
 'P':15,
 'Q':12,
 'R':19,
 'S':2,
 'T':14,
 'U':17,
 'V':20,
 'W':25,
 'X':24,
 'Y':10,
 'Z':26
}
 
```

Por ejemplo, el mensaje "MARCIANOS" lo codificaríamos como "21 8 19 5 4 8 1 6 2"

Para poder enviar mensajes, debemos introducir los dígitos en una matriz 3x3. En este ejemplo, la matriz sería:

$$A=\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}$$

A continuación, hay que multiplicar por la izquierda esta matriz por otra proporcionada por el Gobierno:

$$C=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}$$

Por tanto, el mensaje resultante sería:

$$Z = CA=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}=\begin{bmatrix}43 & 22 & 40 \\ 22 & 14 & 21 \\ 5 & 4 & 8\end{bmatrix}$$

El receptor del mensaje deberá decodificarlo multiplicando la matriz $Z$ por la matriz $C^{-1}$ (por la izquierda):

$$C^{-1}Z=A$$

**SE PIDE:**
1. Implementa una función para enviar mensajes de 9 letras codificados
> 1.1 Genera los dígitos correspondientes al mensaje a partir del diccionario y guárdalo en una lista  
> 1.2 Haz un reshape de la lista para transformarlo en un array de numpy 3x3  
> 1.3 Genera la matriz $Z=CA$, que será el output de la función
2. Implementa una función para decodificar mensajes de 9 letras
> 2.1 Crea un nuevo diccionario, donde se inviertan las claves y los valores del original  
> 2.2 Realiza la operación $C^{-1}Z=A$ y convierte la matriz a un vector con el método `flatten()`  
> 2.3 Recorre los elementos del vector para generar el mensaje decodificado usando el diccionario creado en 2.1

Consejo: Antes de implementar la función, reproduce el ejemplo del enunciado. Cuando te funcione, encapsula tu código en funciones

In [32]:
dicc_claves = {'A':8,
               'B':7,
               'C':5,
               'D':13,
               'E':9,
               'F':16,
               'G':18,
               'H':22,
               'I':4,
               'J':23,
               'K':11,
               'L':3,
               'M':21,
               'N':1,
               'O':6,
               'P':15,
               'Q':12,
               'R':19,
               'S':2,
               'T':14,
               'U':17,
               'V':20,
               'W':25,
               'X':24,
               'Y':10,
               'Z':26
              }

#mensaje = [4, 1, 20, 8, 13, 4, 13, 6, 2]
#invadidos

def enviar_mensaje(mensaje, C): # tb matriz C porque puede cambiar
    M = []
    for letra in mensaje:
        M.append(dicc_claves[letra])
    #print(M)

    A = np.array([M]).reshape(3, 3)
   
    Z = C.dot(A)
    return Z

C = np.array([[2, 0, 1],
             [1, 0, 1],
             [0, 1, 0]])    
    
Z = enviar_mensaje("INVADIDOS", C) # guardar en variable proque si no no lo reconoce después en 2ª parte 
Z

array([[21,  8, 42],
       [17,  7, 22],
       [ 8, 13,  4]])

In [34]:
dicc_inv = {v: k for k, v in dicc_claves.items()} 
# print(dicc_inv)
# para invertir el dicc por método clásico:
# for key, value in dicc_claves.items():
    # dicc_inv[value] = key

C = np.array([[2, 0, 1],
              [1, 0, 1],
              [0, 1, 0]])
Z

def decod(Z, C):
    C_inv = np.linalg.inv(C)
    M2 = C_inv.dot(Z)
    A2 = M2.flatten()
    # print(A)
    D = "" # yo lo había hecho con lista D=[], mejor str
    for num in A2:
        D += dicc_inv[num] # D.append(dicc_inv[num])
    
    return D

mensaje = decod(Z, C)
mensaje

'INVADIDOS'

In [21]:
M = []
mensaje = "MARCIANOS"
for letra in mensaje:
    M.append(dicc_claves[letra]) # así puedo acceder a los valores del diccionario
print(M)

[21, 8, 19, 5, 4, 8, 1, 6, 2]


# Ejercicio 3 

En el álgebra de matrices, existen tres tipos de matrices de especial interés:

1. **Matriz diagonal**: Todos los elementos son 0 excepto los de la diagonal
<img src='./img/diagonal.png' width = 200>

2. **Triangular superior**: Todos los elementos por encima de la diagonal son 0
<img src='./img/upper.png' width = 200>

3. **Triangular inferior**: Todos los elementos por debajo de la diagonal son 0
<img src='./img/lower.png' width = 200>

En numpy, las funciones `diag()`, `triu()` y `tril()` permiten hacer transformaciones de una matriz a cualquiera de las 3 anteriores

**CASO DE USO**


<img src='./img/bets.jpg' width=400>


En LaLiga se generan matrices como la siguiente, que indican la probabilidad estimada de cada resultado en un determinado partido:  

![SegmentLocal](./img/match_matrix.gif "segment")

Por ejemplo, la probabilidad estimada de que acaben 1-2 es del 3.37%  
La probabilidad de que acaben en empate sería la suma de la diagonal: $(0.0373+0.078+0.0409+0.0095+0.0012+0.0001)=16.7\%$

**SE PIDE**: 

1. Implementa una función que reciba una matriz cuadrada nxn y devuelva un diccionario con la probabilidad de empate, victoria local y victoria visitante. Asegúrate de que la suma de estas tres probabilidades es próxima a 1.

2. Implementa otra función que transforme el diccionario con las probabilidades a un diccionario de cuotas redondeado a 2 decimales (la cuota la calculamos como la inversa de la probabilidad)

Prueba con esta matriz
$$ P=\begin{bmatrix}0.0373 & 0.082 & 0.013 & 0.004\\ 0.1504 & 0.098 & 0.0337 & 0.0097 \\
0.121 & 0.194 & 0.04 & 0.0118 \\ 0.088 &  0.076 & 0.032 & 0.0091\end{bmatrix}$$

In [41]:
import numpy as np
probs = np.array([[0.0373, 0.082, 0.013, 0.004],
                  [0.1504, 0.098, 0.0337, 0.0097],
                  [0.121, 0.194, 0.04, 0.0118],
                  [0.088, 0.076, 0.032, 0.0091]
                 ])
print(np.sum(probs)) # me aseguro de que suma 1

1.0


In [46]:
#1)
emp = np.diag(probs)
print(emp)

home = np.triu(probs, k = 1) # para que la diagonal = 0, k=1
print(home)

away = np.tril(probs, k = -1) # diagonal = 0, k = -1
print(away)

[0.0373 0.098  0.04   0.0091]
[[0.     0.082  0.013  0.004 ]
 [0.     0.     0.0337 0.0097]
 [0.     0.     0.     0.0118]
 [0.     0.     0.     0.    ]]
[[0.     0.     0.     0.    ]
 [0.1504 0.     0.     0.    ]
 [0.121  0.194  0.     0.    ]
 [0.088  0.076  0.032  0.    ]]


In [48]:
empate = np.sum(emp)
local = np.sum(home)
vis = np.sum(away)
print(empate, local, vis)

0.1844 0.1542 0.6614


In [54]:
def prob1x2(matriz):
    empate = np.sum(np.diag(matriz))
    local = np.sum(np.triu(matriz, k = 1))
    vis = np.sum(np.tril(matriz, k = -1))
    
    return {"Prob empate":empate, "Prob local":local, "Prob vis":vis}

res = prob1x2(probs)    
res

{'Prob empate': 0.1844, 'Prob local': 0.1542, 'Prob vis': 0.6614}

In [55]:
#2)
cuota1 = round(1/res["Prob empate"], 2)
cuota2 = round(1/res["Prob local"], 2)
cuota3 = round(1/res["Prob vis"], 2)
print(cuota1, cuota2, cuota3)

5.42 6.49 1.51


In [60]:
def cuotas(diccionario):
    cuota1 = round(1/res["Prob empate"], 2)
    cuota2 = round(1/res["Prob local"], 2)
    cuota3 = round(1/res["Prob vis"], 2)
    
    return {"Empate":cuota1, "Local":cuota2, "Vis":cuota3}

cuotas(prob1x2(probs))    

{'Empate': 5.42, 'Local': 6.49, 'Vis': 1.51}