![imagen](./img/espectadores.jpg)

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio creación de arrays en numpy</h3>

      
<ol>
    <li>Crea un array con 3 deportes que te gusten</li>
    <li>Accede al primer elemento y al último</li>
    <li>Comprueba los tipos de los datos</li>
    <li>Crea una secuencia de numeros del 10 al 0, con saltos de -0.5</li>
    <li>Crea una matriz de 5x2 con numeros enteros aleatorios comprendidos entre el 10 y el 20</li>
</ol>
         
 </td></tr>
</table>

In [2]:
import numpy as np
# Celda para soluciones
array1 = np.array(["MMA", "Futbol", "Baloncesto"])
print(array1)
print(array1[0], array1[-1])
print(array1.dtype)
array4 = np.arange(10, -0.5, -0.5) # Para que llegue al 0
print(array4)
matriz5 = np.random.randint(10, 20, size=(5,2))
print(matriz5)

['MMA' 'Futbol' 'Baloncesto']
MMA Baloncesto
<U10
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5  1.   0.5  0. ]
[[12 19]
 [19 14]
 [11 11]
 [11 17]
 [19 15]]


<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio slicing</h3>

      
<ol>
    <li>Todos los elementos, pero de dos en dos</li>
    <li>Todos los elementos, pero de dos en dos, a partir del segundo item</li>
    <li>Todo, pero invertido</li>
    <li>Obtén los últimos dos items, y muéstralos invertidos</li>
    <li>Todo, excepto los ultimos dos items, y muéstralos invertidos.</li>
</ol>
         
 </td></tr>
</table>

In [28]:
secuencia = np.arange(10, 0, -0.5)
print(secuencia[::2])
print(secuencia[1::2])
print(secuencia[::-1])
print(secuencia[:-3:-1])
print(secuencia[-3::-1])

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[9.5 8.5 7.5 6.5 5.5 4.5 3.5 2.5 1.5 0.5]
[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]
[0.5 1. ]
[ 1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.
  8.5  9.   9.5 10. ]


## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [30]:
import numpy as np
# Celda para soluciones
array_slicing = np.array([1,2,3,4,5,6,7,8,9])
print(array_slicing[::2]) # 1
print(array_slicing[1::2]) #2
print(array_slicing[::-1]) # 3
print(array_slicing[-1:-3:-1]) # 3
print(array_slicing[-3:0:-1])

'1.26.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [32]:
my_array = np.arange(10)
my_array_copia = my_array.copy()
print(my_array)

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [53]:
arrayTrue3x3 = np.full((3,3), True)
print(arrayTrue3x3)

dtype('<U1')

[['2' '2' '2']
 ['2' '2' '2']
 ['2' '2' '2']]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [ ]:
filtro = np.array(my_array %2 != 0)
array_impares = my_array[filtro]
print(array_impares)

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [ ]:
my_array_menos1 = np.where(my_array % 2 != 0, -1, my_array)
print(my_array_menos1)

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [17]:
filtro = np.array(my_array %2 != 0)
my_array[filtro] = -1
print(my_array) 

-1


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [21]:
my_array = np.arange(10)
my_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [22]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [3]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
comun = np.intersect1d(a, b)
print(comun)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?