![imagen](./img/espectadores.jpg)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import pandas as pd
import numpy as np
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [2]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [3]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [106]:
my_matrix = np.arange(1, 21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [107]:
inv_my_natrix = my_matrix.T # Estoy entiendo por invertir, porque invertir como tal una matriz 4x5 no es posible
inv_my_natrix = my_matrix[::-1] # o esto, no estoy seguro

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [114]:
print(my_matrix)
print(my_matrix[0:2, 0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [118]:
print(my_matrix)
print(my_matrix[0::2, 0:5:2]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [121]:
print(my_matrix)
print(my_matrix[0:3, ::-1]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [83]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [95]:
x_filtrado = np.array(x == 'Loro')
x[x_filtrado]

array(['Loro', 'Loro'], dtype='<U5')

In [101]:
forma2 = [i for i in x if i == 'Loro']
forma2

['Loro', 'Loro']

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [104]:
y = np.arange(20).reshape(2,5,2)
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [129]:
print(my_matrix)
print(my_matrix[-1::-1, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [134]:
zeros = np.zeros((2,5))
print(zeros.nbytes)
zeros[0, 3] = 1
zeros

80


array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [140]:
vector = np.arange(10,50)
vector_invertido = vector[::-1]
vector_invertido

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [145]:
vector_ej13 = np.array([1,2,0,0,4,0])

In [147]:
output = [i for i, j in enumerate(vector) if j != 0]
output

[0, 1, 4]

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [169]:
randomMatrix = np.random.randint(10 , size=(10,10))
minimo = np.min(randomMatrix)
maximo = np.max(randomMatrix)
print(minimo, maximo)

0 9


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [171]:
random_vector = np.random.randint(10, size=(1,30))
random_vector.mean()

4.833333333333333

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [173]:
def cuadrado2D(dimensiones): 
    arrayOnes = np.ones((dimensiones, dimensiones))
    arrayOnes[1:-1, 1:-1] = 0
    return arrayOnes

print(cuadrado2D(8))

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [182]:
matrix_ej17 = np.ones((8, 8))
matrix_ej17[::2, ::2] = 0
matrix_ej17[1::2, 1::2] = 0

matrix_ej17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [186]:
secuencia = np.array([[0, 1],
                     [1, 0]])
np.tile(secuencia, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [187]:
matriz = np.random.randint(10, size=(5,5))
media = matriz.mean()
desviacion = matriz.std()
matriz = (matriz - media)/desviacion
matriz

array([[ 1.7163882 , -1.92688864, -0.30765449, -1.5220801 ,  0.09715405],
       [-0.30765449, -0.71246303, -0.71246303, -0.71246303, -0.71246303],
       [ 1.31157966, -0.71246303,  0.09715405, -1.92688864,  0.09715405],
       [ 0.09715405,  0.50196259,  1.31157966,  0.09715405,  0.09715405],
       [-0.30765449,  1.7163882 ,  0.90677113,  1.31157966,  0.50196259]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [199]:
primero = np.arange(11)
segundo = primero.copy()
segundo[(primero<=8) & (primero>=3)] = -1
tercero = primero.copy()
tercero[((primero<=8) & (primero>=3))] *= -1
print(primero, segundo, tercero)

[ 0  1  2  3  4  5  6  7  8  9 10] [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10] [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [366]:
import numpy as np
import random

# 1º
tablero = np.full((10,10), '()')

# 2º
tablero[0:2,1] = 'O'
tablero[1, 3:7] = 'O'

# 3º
def disparo(coordenadas, tablero):
    coordenada_fila = coordenadas[0]
    coordenada_columna = coordenadas[1]
    if tablero[coordenada_fila, coordenada_columna] == 'O':
        tablero[coordenada_fila, coordenada_columna] = 'X'
    else:
        tablero[coordenada_fila, coordenada_columna] = '~'
    return tablero
# disparo a barco
#print(disparo([1,1], tablero))
#print("\n")
# Disparo al agua
#print(disparo([3,3], tablero))

# 5º
# Ignoramos disparos recibidos (actualizar tablero):
tablero = np.full((10,10), '()')
tablero[0:2,1] = ' O'
tablero[1, 3:7] = ' O' # Lo ponemos un espacio para que quede bien

def encajar_barco(tablero): # los print son para debuggear.
    while True:
        posicion_inicial = [random.randint(0,9), random.randint(0,9)]
        orientacion = random.choices(['N', 'S', 'E', 'O'])[0]
        print(posicion_inicial, orientacion)
        if orientacion == 'N':
            if posicion_inicial[0] - 4 > 0:  # No se sobrepasa por arriba
                lista = tablero[posicion_inicial[0] - 3: posicion_inicial[0] + 1, posicion_inicial[1]] == '()' # tenemos que restar 3 y sumar 1 porque en norte y oeste estamos iterando 'hacia atras' por lo que restarle 4 no nos daria el resultado adecuado
                print(lista)
                if False in lista: # Al menos una posicion esta ocupada
                    pass
                else:
                    tablero[posicion_inicial[0] - 3: posicion_inicial[0] + 1, posicion_inicial[1]] = ' O'
                    break
        elif orientacion == 'S':
            if posicion_inicial[0] + 4 < 10:  # No se sobrepasa por abajo
                lista = tablero[posicion_inicial[0]: posicion_inicial[0] + 4, posicion_inicial[1]] == '()' # En sur y este sumamos 4 sin mas, porque estamos iterando 'hacia delante'.
                print(lista)
                if False in lista: 
                    pass
                else:
                    tablero[posicion_inicial[0]: posicion_inicial[0] + 4, posicion_inicial[1]] = ' O'
                    break
        elif orientacion == 'E':
            if posicion_inicial[1] + 4 < 10:  # No se sobrepasa por la derecha
                lista = tablero[posicion_inicial[0], posicion_inicial[1]: posicion_inicial[1] + 4] == '()'
                print(lista)
                if False in lista: 
                    pass
                else:
                    tablero[posicion_inicial[0], posicion_inicial[1]: posicion_inicial[1] + 4] = ' O'
                    break
        elif orientacion == 'O':
            if posicion_inicial[1] - 4 > 0:  # No se sobrepasa por la izquierda
                lista = tablero[posicion_inicial[0], posicion_inicial[1] - 3: posicion_inicial[1] + 1] == '()'
                print(lista)
                if False in lista: 
                    pass
                else:
                    tablero[posicion_inicial[0], posicion_inicial[1] - 3: posicion_inicial[1] + 1] = ' O'
                    break
        else:
            print("Hay alguna opcion sin considerar")
    return tablero # devuelve el tablero cuando termine el bucle


print(encajar_barco(tablero))

[4, 8] E
[5, 1] O
[1, 4] E
[False False False  True]
[1, 1] N
[0, 0] N
[6, 2] E
[ True  True  True  True]
[['()' ' O' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' ' O' '()' ' O' ' O' ' O' ' O' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' ' O' ' O' ' O' ' O' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']]
